services:
  pasttel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pasttel_container
    command: tail -f /dev/null
    volumes:
      - ./test-reports:/app/pasttel/test-reports
